FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN DATABASE_URL=postgresql://placeholder:placeholder@db:5432/placeholder npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
